name: Brian Taylor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82963
title: Brian Taylor - Digital Marketing Professional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76885420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000008'
    - '#244068'
    - '#fbf9fa'
    - '#9c897a'
    - '#dfd6d1'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
