name: Brian Taylor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82963
title: Brian Taylor - Digital Marketing Professional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76885420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c7c9c6'
    - '#444945'
    - '#919692'
    - '#298a9b'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
