name: Brian Taylor
favicon: null
layout_spectrum: 0.67369
typography_spectrum: 0.82963
title: Brian Taylor - Digital Marketing Professional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76885420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e5eb'
    - '#1c1c1c'
    - '#c5bfc1'
    - '#515153'
    - '#7b7d80'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
