name: Brian Taylor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82963
title: Brian Taylor - Digital Marketing Professional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76885420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efedee'
    - '#242843'
    - '#e2b2ae'
    - '#59657b'
    - '#a08478'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
