name: Brian Taylor
favicon: null
layout_spectrum: 0.75391
typography_spectrum: 0.82963
title: Brian Taylor - Digital Marketing Professional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76885420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#010008'
    - '#d0c9bf'
    - '#524233'
    - '#746f5c'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
